{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeversion-exporter
  labels:
{{ include "kubeversion-exporter.labels" . | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
{{ end }}
