{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kubeversion-exporter.fullname" . }}
  labels:
{{ include "kubeversion-exporter.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeversion-exporter
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ template "kubeversion-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
