{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubeversion-exporter.serviceAccountName" . }}
  labels:
{{ include "kubeversion-exporter.labels" . | indent 4 }}
{{ end }}
